export enum LoadingStatusEnum {
    LOADING = "loading",
    LOADED = "loaded",
    ERROR = "error",
    INITIAL = "initial",
}

export const LOGIN_USER_REQUEST = "LOGIN_USERS_REQUEST";
export const LOGOUT_USER_REQUEST = "LOGOUT_USERS_REQUEST";

export const GET_REFERRAL_LINKS_REQUEST = "GET_REFERRAL_LINKS_REQUEST";
export const GET_REFERRAL_LINK_REQUEST = "GET_REFERRAL_LINK_REQUEST";
export const GET_REFERRAL_LINK_BY_TITLE_REQUEST = "GET_REFERRAL_LINK_BY_TITLE_REQUEST";
export const INCREMENT_REFERRAL_LINK_CLICKS_REQUEST = "INCREMENT_REFERRAL_LINK_CLICKS_REQUEST";
export const ADD_REFERRAL_LINK_REQUEST = "ADD_REFERRAL_LINK_REQUEST";
export const EDIT_REFERRAL_LINK_REQUEST = "EDIT_REFERRAL_LINK_REQUEST";
export const DELETE_REFERRAL_LINK_REQUEST = "DELETE_REFERRAL_LINK_REQUEST";